import { SourceTextGenerator } from '@/features/common/projects/SourceTextGenerator';

export class DotnetGitignoreGenerator extends SourceTextGenerator {
	generate(optionalLines: string[] = []): string {
		const lines: string[] = [];
		lines.push(
			'## Ignore Visual Studio temporary files, build results, and',
		);
		lines.push('## files generated by popular Visual Studio add-ons.');
		lines.push('##');
		lines.push(
			'## Get latest from https://github.com/github/gitignore/blob/master/VisualStudio.gitignore',
		);
		lines.push('');
		lines.push('# User-specific files');
		lines.push('*.suo');
		lines.push('*.user');
		lines.push('*.userosscache');
		lines.push('*.sln.docstates');
		lines.push('');
		lines.push('# User-specific files (MonoDevelop/Xamarin Studio)');
		lines.push('*.userprefs');
		lines.push('');
		lines.push('# Build results');
		lines.push('[Dd]ebug/');
		lines.push('[Dd]ebugPublic/');
		lines.push('[Rr]elease/');
		lines.push('x64/');
		lines.push('x86/');
		lines.push('bld/');
		lines.push('[Bb]in/');
		lines.push('[Oo]bj/');
		lines.push('[Ll]og/');
		lines.push('');
		lines.push('# Visual Studio 2015 cache/options directory');
		lines.push('.vs/');
		lines.push(
			"# Uncomment if you have tasks that create the project's static files in wwwroot",
		);
		lines.push('#wwwroot/');
		lines.push('');
		lines.push('# MSTest test Results');
		lines.push('[Tt]est[Rr]esult*/');
		lines.push('[Bb]uild[Ll]og.*');
		lines.push('');
		lines.push('# NUNIT');
		lines.push('*.VisualState.xml');
		lines.push('TestResult.xml');
		lines.push('');
		lines.push('# Build Results of an ATL Project');
		lines.push('[Dd]ebugPS/');
		lines.push('[Rr]eleasePS/');
		lines.push('dlldata.c');
		lines.push('');
		lines.push('# .NET Core');
		lines.push('project.lock.json');
		lines.push('project.fragment.lock.json');
		lines.push('artifacts/');
		lines.push('**/Properties/launchSettings.json');
		lines.push('');
		lines.push('# VS Code');
		lines.push('.vscode/');
		lines.push('');
		lines.push('*_i.c');
		lines.push('*_p.c');
		lines.push('*_i.h');
		lines.push('*.ilk');
		lines.push('*.meta');
		lines.push('*.obj');
		lines.push('*.pch');
		lines.push('*.pdb');
		lines.push('*.pgc');
		lines.push('*.pgd');
		lines.push('*.rsp');
		lines.push('*.sbr');
		lines.push('*.tlb');
		lines.push('*.tli');
		lines.push('*.tlh');
		lines.push('*.tmp');
		lines.push('*.tmp_proj');
		lines.push('*.log');
		lines.push('*.vspscc');
		lines.push('*.vssscc');
		lines.push('.builds');
		lines.push('*.pidb');
		lines.push('*.svclog');
		lines.push('*.scc');
		lines.push('');
		lines.push('# Chutzpah Test files');
		lines.push('_Chutzpah*');
		lines.push('');
		lines.push('# Visual C++ cache files');
		lines.push('ipch/');
		lines.push('*.aps');
		lines.push('*.ncb');
		lines.push('*.opendb');
		lines.push('*.opensdf');
		lines.push('*.sdf');
		lines.push('*.cachefile');
		lines.push('*.VC.db');
		lines.push('*.VC.VC.opendb');
		lines.push('');
		lines.push('# Visual Studio profiler');
		lines.push('*.psess');
		lines.push('*.vsp');
		lines.push('*.vspx');
		lines.push('*.sap');
		lines.push('');
		lines.push('# TFS 2012 Local Workspace');
		lines.push('$tf/');
		lines.push('');
		lines.push('# Guidance Automation Toolkit');
		lines.push('*.gpState');
		lines.push('');
		lines.push('# ReSharper is a .NET coding add-in');
		lines.push('_ReSharper*/');
		lines.push('*.[Rr]e[Ss]harper');
		lines.push('*.DotSettings.user');
		lines.push('');
		lines.push('# JustCode is a .NET coding add-in');
		lines.push('.JustCode');
		lines.push('');
		lines.push('# TeamCity is a build add-in');
		lines.push('_TeamCity*');
		lines.push('');
		lines.push('# DotCover is a Code Coverage Tool');
		lines.push('*.dotCover');
		lines.push('');
		lines.push('# Visual Studio code coverage results');
		lines.push('*.coverage');
		lines.push('*.coveragexml');
		lines.push('');
		lines.push('# NCrunch');
		lines.push('_NCrunch_*');
		lines.push('.*crunch*.local.xml');
		lines.push('nCrunchTemp_*');
		lines.push('');
		lines.push('# MightyMoose');
		lines.push('*.mm.*');
		lines.push('AutoTest.Net/');
		lines.push('');
		lines.push('# Web workbench (sass)');
		lines.push('.sass-cache/');
		lines.push('');
		lines.push('# Installshield output folder');
		lines.push('[Ee]xpress/');
		lines.push('');
		lines.push('# DocProject is a documentation generator add-in');
		lines.push('DocProject/buildhelp/');
		lines.push('DocProject/Help/*.HxT');
		lines.push('DocProject/Help/*.HxC');
		lines.push('DocProject/Help/*.hhc');
		lines.push('DocProject/Help/*.hhk');
		lines.push('DocProject/Help/*.hhp');
		lines.push('DocProject/Help/Html2');
		lines.push('DocProject/Help/html');
		lines.push('');
		lines.push('# Click-Once directory');
		lines.push('publish/');
		lines.push('');
		lines.push('# Publish Web Output');
		lines.push('*.[Pp]ublish.xml');
		lines.push('*.azurePubxml');
		lines.push(
			'# TODO: Comment the next line if you want to checkin your web deploy settings',
		);
		lines.push(
			'# but database connection strings (with potential passwords) will be unencrypted',
		);
		lines.push('*.pubxml');
		lines.push('*.publishproj');
		lines.push('');
		lines.push(
			'# Microsoft Azure Web App publish settings. Comment the next line if you want to',
		);
		lines.push(
			'# checkin your Azure Web App publish settings, but sensitive information contained',
		);
		lines.push('# in these scripts will be unencrypted');
		lines.push('PublishScripts/');
		lines.push('');
		lines.push('# NuGet Packages');
		lines.push('*.nupkg');
		lines.push(
			'# The packages folder can be ignored because of Package Restore',
		);
		lines.push('**/packages/*');
		lines.push('# except build/, which is used as an MSBuild target.');
		lines.push('!**/packages/build/');
		lines.push(
			'# Uncomment if necessary however generally it will be regenerated when needed',
		);
		lines.push('#!**/packages/repositories.config');
		lines.push(
			"# NuGet v3's project.json files produces more ignorable files",
		);
		lines.push('*.nuget.props');
		lines.push('*.nuget.targets');
		lines.push('');
		lines.push('# Microsoft Azure Build Output');
		lines.push('csx/');
		lines.push('*.build.csdef');
		lines.push('');
		lines.push('# Microsoft Azure Emulator');
		lines.push('ecf/');
		lines.push('rcf/');
		lines.push('');
		lines.push('# Windows Store app package directories and files');
		lines.push('AppPackages/');
		lines.push('BundleArtifacts/');
		lines.push('Package.StoreAssociation.xml');
		lines.push('_pkginfo.txt');
		lines.push('');
		lines.push('# Visual Studio cache files');
		lines.push('# files ending in .cache can be ignored');
		lines.push('*.[Cc]ache');
		lines.push('# but keep track of directories ending in .cache');
		lines.push('!*.[Cc]ache/');
		lines.push('');
		lines.push('# Others');
		lines.push('ClientBin/');
		lines.push('~$*');
		lines.push('*~');
		lines.push('*.dbmdl');
		lines.push('*.dbproj.schemaview');
		lines.push('*.jfm');
		lines.push('*.pfx');
		lines.push('*.publishsettings');
		lines.push('orleans.codegen.cs');
		lines.push('');
		lines.push(
			'# Since there are multiple workflows, uncomment next line to ignore bower_components',
		);
		lines.push(
			'# (https://github.com/github/gitignore/pull/1529#issuecomment-104372622)',
		);
		lines.push('#bower_components/');
		lines.push('');
		lines.push('# RIA/Silverlight projects');
		lines.push('Generated_Code/');
		lines.push('');
		lines.push(
			'# Backup & report files from converting an old project file',
		);
		lines.push(
			'# to a newer Visual Studio version. Backup files are not needed,',
		);
		lines.push('# because we have git ;-)');
		lines.push('_UpgradeReport_Files/');
		lines.push('Backup*/');
		lines.push('UpgradeLog*.XML');
		lines.push('UpgradeLog*.htm');
		lines.push('');
		lines.push('# SQL Server files');
		lines.push('*.mdf');
		lines.push('*.ldf');
		lines.push('');
		lines.push('# Business Intelligence projects');
		lines.push('*.rdl.data');
		lines.push('*.bim.layout');
		lines.push('*.bim_*.settings');
		lines.push('');
		lines.push('# Microsoft Fakes');
		lines.push('FakesAssemblies/');
		lines.push('');
		lines.push('# GhostDoc plugin setting file');
		lines.push('*.GhostDoc.xml');
		lines.push('');
		lines.push('# Node.js Tools for Visual Studio');
		lines.push('.ntvs_analysis.dat');
		lines.push('node_modules/');
		lines.push('');
		lines.push('# Typescript v1 declaration files');
		lines.push('typings/');
		lines.push('');
		lines.push('# Visual Studio 6 build log');
		lines.push('*.plg');
		lines.push('');
		lines.push('# Visual Studio 6 workspace options file');
		lines.push('*.opt');
		lines.push('');
		lines.push(
			'# Visual Studio 6 auto-generated workspace file (contains which files were open etc.)',
		);
		lines.push('*.vbw');
		lines.push('');
		lines.push('# Visual Studio LightSwitch build output');
		lines.push('**/*.HTMLClient/GeneratedArtifacts');
		lines.push('**/*.DesktopClient/GeneratedArtifacts');
		lines.push('**/*.DesktopClient/ModelManifest.xml');
		lines.push('**/*.Server/GeneratedArtifacts');
		lines.push('**/*.Server/ModelManifest.xml');
		lines.push('_Pvt_Extensions');
		lines.push('');
		lines.push('# Paket dependency manager');
		lines.push('.paket/paket.exe');
		lines.push('paket-files/');
		lines.push('');
		lines.push('# FAKE - F# Make');
		lines.push('.fake/');
		lines.push('');
		lines.push('# JetBrains Rider');
		lines.push('.idea/');
		lines.push('*.sln.iml');
		lines.push('');
		lines.push('# CodeRush');
		lines.push('.cr/');
		lines.push('');
		lines.push('# Python Tools for Visual Studio (PTVS)');
		lines.push('__pycache__/');
		lines.push('*.pyc');
		lines.push('');
		lines.push('# Cake - Uncomment if you are using it');
		lines.push('# tools/**');
		lines.push('# !tools/packages.config');
		lines.push('');
		lines.push("# Telerik's JustMock configuration file");
		lines.push('*.jmconfig');
		lines.push('');
		lines.push('# BizTalk build output');
		lines.push('*.btp.cs');
		lines.push('*.btm.cs');
		lines.push('*.odx.cs');
		lines.push('*.xsd.cs');
		if (optionalLines.length > 0) {
			lines.push('');
			lines.push(...optionalLines);
		}
		return this.joinLines(lines);
	}
}
